In [1]:
#Numpy배열과 list차이
    #Numpy - 같은 구조로 연속된 자료 -> 벡터화 연산 가능/복잡한 수식 계산 가능
    #list - 각 자료마다 크기가 다르고 위치가 연속적이지 않음
    #Numpy가 상대적으로 속도가 빠르고 메모리를 적게 차지함

#Numpy는 자료를 변경 불가, 모두 같은 자료형으로만 


In [3]:
#li = [1,2,3,4,5,6,7,8,9,10]
#li*10 -> li가 총 10번 반복 출력 됨
#각 요소에 대한 계산 불가능

In [ ]:
!conda list

In [3]:
#Numpy패키지
#anaconda에 기본적으로 포한되어 설치된 라이브러리
#별칭은 np라는 이름으로 임포트

import numpy as np


In [70]:
##1차원 배열 

#.array()
#ndarray 클래스 객체, Numpy 배열로 변환
#np.array() -> return ndarray 

ar = np.array([ _ for _ in range(10)])
ar


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#정수와 실수가 혼합된 경우
#표현 범위가 더 큰 자료형으로 변환 -> 모두 실수로 변환

ar2 = np.array([0.1,5,4,12,0.5])
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [19]:
#np.array()로 생성한 객체는 numpy.ndarray 타입을 갖는다.
type(ar)

numpy.ndarray

In [71]:
#.shape() 
#넘파이 배열의 모양 확인
#(10,) -> 1차원의 10칸 갖는 ndarray 모양

ar.shape

(10,)

In [33]:
#dtype지정
x = np.array([1,2,3],dtype='f')

y = np.array([1,2,3],dtype='U')

In [37]:
#ndarray도 인덱싱 가능
x[0] + x[1]

3.0

In [38]:
#.dtype
#넘파이 배열의 자료형 확인
#크기 지정 안해도 Numpy에서 지정 -> 가장 큰 글자가 한글자라서 크기는 1로 
y.dtype

dtype('<U1')

In [42]:
x = [0, 1, -1, 0]
y = [1, 0, 0, 0]

# x/y -> 리스트끼리의 연산은 불가능

xn = np.array(x)
yn = np.array(y)

In [43]:
#.inf : 무한대(infinity)
#.nan : 정의할 수 없는 숫자(not a number)

xn / yn

C:\Users\user\AppData\Local\Temp\ipykernel_13288\1069198053.py:4: RuntimeWarning: divide by zero encountered in true_divide
  xn / yn
C:\Users\user\AppData\Local\Temp\ipykernel_13288\1069198053.py:4: RuntimeWarning: invalid value encountered in true_divide
  xn / yn


array([  0.,  inf, -inf,  nan])

In [53]:
#벡터화 연산
#배열의 각 요소에 대한 반복 연산

#각 요소가 2배가 되는 연산
#리스트
    #for문으로 각 요소를 꺼내오고 각각에 *2를 해줘야 함
    #[_* 2 for _ in range(10)]

#넘파이 배열 객체
data = [0,1,2,3,4,5,6,7,8,9]
x = np.array(data)
x * 2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
a = np.array([1,2,3])
b = np.array([10,20,30])

a == 2
#a == np.array([2,2,2])

array([False,  True, False])

In [58]:
b < 20
#b < np.array([20,20,20])

array([ True, False, False])

In [67]:
b > 10

array([False,  True,  True])

In [69]:
# & 연산자 (=and)
# 모두 T(or F)이면 T(or F) , 하나라도 F이면 F
#Numpy에서는 and 사용하면 error

(a==2) & (b >10)

# 연산자 우선순위 떄문에 ()없으면 error
# a==2 & b >10

array([False,  True, False])

In [75]:
#2차원 배열 (=행렬 matrix)
#중첩된 리스트 이용

c = np.array([[0,1,2],[3,4,5]])   #2 X 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
c.shape   #2행 3열

(2, 3)

In [79]:
#행의 갯수
len(c)   

2

In [83]:
#열의 갯수
len(c[0])

3

In [82]:
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [86]:
#3차원 배열
#리스트 3번 중첩
#가장 바깥쪽 리스트의 길이부터 안쪽 리스트 길이의 순서로 표시

#2 X 3 X 4
d =np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [88]:
len(d),len(d[0]),len(d[0][0])    #소괄호가 생략된 튜플 

(2, 3, 4)

In [89]:
#ndim : 배열의 차원
#shape : 배열의 크기

print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [95]:
#1차원 배열의 인덱싱 (=리스트 인덱싱)

a = np.array([0,1,2,3,4])
a[-1]

4

In [120]:
#다차원 배열의 인덱싱

test = [[1,2,3,4],[5,6,7,8]]   #list
test[1][1]                     #6

a = np.array([[0,1,2],[3,4,5]]) #ndarray
a

print(a.shape)     #인덱싱 -> a[0~!,0~2]
print(a.ndim)


(2, 3)
2


In [121]:
a[0,:]    #첫 번째 행 전체

array([0, 1, 2])

In [122]:
a[1,1:]

array([4, 5])

In [118]:
c = [[1,2,3,4],[5,6,7,8]] #list
c[0][:3]    # a에서 1,2,3의 값 가져오기

[1, 2, 3]

In [123]:
m=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

In [124]:
m[1,2]

7

In [125]:
m[2,-1]

14

In [126]:
m[1,1:3]

array([6, 7])

In [127]:
m[1:,2]

array([ 7, 12])

In [130]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [132]:
#zeros 
#모든 값이 0인 배열 생성

a = np.zeros(5, dtype='U4')
a

array(['', '', '', '', ''], dtype='<U4')

In [137]:
a[0] ='abc'
a[1] = 'abcd'
a[2] = 'ABCDE'  #dtype='<U4'으로 4글자까지만 
a

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [140]:
#ones
#1로 초기화
e = np.ones((2,3,4),dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [141]:
test = np.array([10,20,30])

In [144]:
#_like(배열,dtype)
#인수 배열과 동일한 shape의 배열 생성
np.ones_like(test,dtype='f')

array([1., 1., 1.], dtype=float32)

In [143]:
np.zeros_like(test,dtype='f')

array([0., 0., 0.], dtype=float32)

In [145]:
#empty
#빠르게 배열의 shape을 만들수 있다
g=np.empty((4,3))
g

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313],
       [2.54639495e-313, 2.97079411e-313, 3.39519327e-313],
       [3.81959242e-313, 4.24399158e-313, 4.66839074e-313]])

In [146]:
#arange()
#Numpy버전의 range명령

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
np.arange(3,21,2) #시작, 끝(포함X),단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [152]:
#linspace 
#구간을 선형 간격으로 특정 수 만큼 분할

ex = np.linspace(0,100,5)
ex

array([  0.,  25.,  50.,  75., 100.])

In [154]:
#logspace 
#구간을 로그 간격으로 특정 수 만큼 분할

ex2 = np.logspace(0,100,5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [4]:
#전치 연산 (transpose)
#.T                    -> 메서드가 아닌 속성
#행과 열을 바꿈

A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [158]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [161]:
#배열의 크기 변형
#reshape()

a = np.arange(12)
a

b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [166]:
a.reshape(2,-1,2).shape  #-1은 Numpy 알아서 나눠떨어지게 해라.

(2, 3, 2)

In [168]:
# a.reshape(7,-1)   #-1사용하려면 나눠떨어지는 모양으로 shape 설정해야 함

In [173]:
#1차원으로 변경
#flatten()
#ravel()

a.reshape(2,-1,2).flatten()
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [181]:
#newaxis
#차원만 1차원 증가

a[:,np.newaxis]
#a.ndim

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [192]:
a1 =np.ones((2,3))
a1


array([[1., 1., 1.],
       [1., 1., 1.]])

In [193]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [194]:
##배열 연결(concatenate)
#hstack([])
#배열 수평하게 연결
#행의 수가 같은 배열

np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [196]:
b1 = np.zeros((3,3))
b1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [184]:
#vstack
#위아래로 연결
#열의 수가 같은 배열

In [197]:
np.vstack([a1,b1])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [204]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [205]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [206]:
#dstack
#깊이(depth) 방향으로 배열 합침

np.dstack([c1,c2])   #2개의 (3 X 4) -> 1개의 (3 X 4 X 2)

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [221]:
#stack
#dstack의 확장
#dstack과 달리 사용자가 지정한 차원(축)으로 배열 연결
#axis인수 defalt = 0

#axis = 0 이면 가장 바깥쪽에서 크게 배열 합치기
c= np.stack([c1,c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [215]:
d1 = np.ones((4,5))
d2 = np.zeros((4,5))
d3 = np.arange(20).reshape(4,5)

In [217]:
d1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [218]:
d2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [219]:
d3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [226]:
np.stack([d1,d2,d3],axis = 1)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [10., 11., 12., 13., 14.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [15., 16., 17., 18., 19.]]])

In [228]:
np.stack([d1,d2,d3],axis = 2)

array([[[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 1.,  0.,  2.],
        [ 1.,  0.,  3.],
        [ 1.,  0.,  4.]],

       [[ 1.,  0.,  5.],
        [ 1.,  0.,  6.],
        [ 1.,  0.,  7.],
        [ 1.,  0.,  8.],
        [ 1.,  0.,  9.]],

       [[ 1.,  0., 10.],
        [ 1.,  0., 11.],
        [ 1.,  0., 12.],
        [ 1.,  0., 13.],
        [ 1.,  0., 14.]],

       [[ 1.,  0., 15.],
        [ 1.,  0., 16.],
        [ 1.,  0., 17.],
        [ 1.,  0., 18.],
        [ 1.,  0., 19.]]])

In [229]:
#r_메서드
#기능은  hstack과 동일
#hstack은 (), r_은 []

In [232]:
#c_메서드
#차원을 증가시킨 후 좌우 연결
#1차원 연결하면 2차원

np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [236]:
#tile 
#동일한 배열 반복해서 연결

a =  np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [255]:
zero = np.zeros((3,3))
one = np.ones((3,2))
ten = np.arange(10,160,10)
ten = ten.reshape(3,5)

a = np.vstack([np.hstack([zero,one]),ten])
np.tile(a,(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [256]:
#벡터화 연산
#사칙 연산 , 비교 연산, 논리 연산

a = np.array([1,2,3,4])
b = np.array([4,2,4,2])

In [257]:
a==b

array([False,  True, False, False])

In [258]:
a>=b

array([False,  True, False,  True])

In [259]:
#all()
#모든 원소가 다 같은지 확인

np.all(a==b)

False

In [266]:
#스칼라와 벡터/행렬의 곱

y = np.arange(12).reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [268]:
100 * y

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [274]:
#브로드캐스팅(broadcasting)
#배열끼리 산술 연산은 두 배열의 shapes가 일치해야
#모양이 다른 배열 간의 연산이 가능하도록 배열의 크기를 변환시켜줌
#더 작은 배열이 더 큰 배열에 호환


In [279]:
#스칼라 곱 -> 적은 메모리 사용으로 더 효율적
a = np.array([1.0,2.0,3.0])
b = 2.0                 
a*b           

#브로드캐스팅 동작 구조
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])   
a*b    

array([2., 4., 6.])

In [281]:
#브로드캐스팅 가능한 경우
#넘파이 배열의 shape을 우측 정렬 후 
    #1. 차원 간의 숫자가 동일
    #2. 차원 중 하나가 1인 경우

In [296]:
#차원 축소 연산
#행 하나의 원소들에 대한 평균을 구하면 행에 대해 하나의 숫자가 나옴
#2차원 이상일 때는 axis 키워드 인수 사용

#집계연산
    #최대/최소 :min,max,argmin,argmax
    #통계 :sum,mean,median,std,var
    #불리언 :all,any
    

In [297]:
#sum

x = np.array([1,2,3,4])
x

np.sum(x) #Numpy의 sum메서드
x.sum()   #ndarray의 sum메서드

10

In [291]:
x = np.arange(12).reshape(3,-1)
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [292]:
x.sum(axis=0)

array([12, 15, 18, 21])

In [295]:
x.sum(axis=1)

array([ 6, 22, 38])

In [303]:
#min

x = np.arange(20).reshape(2,5,-1)
x


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [302]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [304]:
x.min(axis=1)

array([[ 0,  1],
       [10, 11]])

In [308]:
#argmin
#제일 작은 값의 인덱스 반환
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [310]:
x.argmin(axis=0)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [311]:
x.argmin(axis=1)

array([[0, 0],
       [0, 0]], dtype=int64)

In [312]:
#max
x.max(axis=1)

array([[ 8,  9],
       [18, 19]])

In [314]:
#argmax
x.argmax(axis=2)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [325]:
m = np.array([[6,4,8,1],[11,3,8,10]])
m


array([[ 6,  4,  8,  1],
       [11,  3,  8, 10]])

In [327]:
m.argmax(axis=1)

array([2, 0], dtype=int64)

In [328]:
#mean() : 평균
#median : 중앙값
#np.all() : 배열이 모두 True이면 True
#np.any() : 하나라도 True 이면 True


In [333]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5,])

In [334]:
((a<=b) & (b<=c)).all()

True

In [330]:
a = np.zeros((100,100),dtype=np.int64)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [331]:
np.any(a != 0)

False

In [332]:
np.all(a==a)

True

In [340]:
practice = np.array([[1.1, 7.1,8.0, 2.1, 6.5, 7.2],
                    [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                    [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                    [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                    [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])
practice

array([[1.1, 7.1, 8. , 2.1, 6.5, 7.2],
       [2.7, 5.2, 3.3, 9. , 7.7, 2.8],
       [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
       [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
       [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [350]:
practice.max()   #전체의 최대값

9.0

In [351]:
practice.sum(axis=0)  #행 간의 합

array([20.1, 27. , 23.6, 26. , 28.2, 26.5])

In [352]:
practice.max(axis=0)  #행 간의 최대값

array([8.2, 8.8, 8. , 9. , 7.7, 8.9])

In [353]:
practice.mean(axis=1)  #열 간의 평균

array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ])

In [354]:
practice.min(axis=1)  #열 간의 최소값

array([1.1, 2.7, 0.7, 0.2, 2.7])

In [355]:
#정렬
#np.sort()
#axis=0 -> 행간 정렬 / axis=1 -> 열간 정렬
#디폴트 값은 -1 -> 가장 안쪽(나중)의 차원

#정렬은 자료의 자체가 변화하는 메서드이므로 주의!



In [376]:
#np.argsort()
#자료의 순서 , 정렬 X
#오름차순 별로 자료의 인덱스 가져옴

a = np.array([42,38,12,25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [360]:
#중요*

a[j]   # argsort의 인덱스를 통해 배열 인덱싱

array([12, 25, 38, 42])

In [366]:
#고급 인덱싱 - 인덱스 배열을 사용한 인덱싱

a = np.array([[1,2],[3,4],[5,6]])
a

print(a[[0,1,2],[0,1,0]])   # [0,1,2] : 행에 대한 인덱스 / [0,1,0]: 열에 대한 인덱스


[1 4 5]


In [375]:
a = np.array([[1,2],[3,4],[5,6]])
a

print(a[:,[0,1,0]])   #a[0][0,1,0] = [1,2,1]
                      #a[1][0,1,0] = [3,4,3]
                      #a[2][0,1,0] = [5,6,5]
        
print(a[::-1,[0,1,0]]) #역순 슬라이싱 

[[1 2 1]
 [3 4 3]
 [5 6 5]]
[[5 6 5]
 [3 4 3]
 [1 2 1]]


In [410]:
scores = np.array([[1,2,3,4],
                   [46,99,100,71],
                   [81,59,90,100]])

eng_sort = np.argsort(scores[1])
print(scores[:,eng_sort])

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


In [464]:
#기술통계

x = np.array([18,5,10,23,19,-8,10,0,0,5,2,15,8,
              2,5,4,15,-1,4,-7,-24,7,9,-6,23,-13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [413]:
len(x)  #개수

26

In [416]:
np.mean(x)  #평균

4.8076923076923075

In [418]:
np.var(x)   #표본 분산

115.23224852071006

In [420]:
np.std(x)   #표본 표준편차

10.734628476137871

In [421]:
np.max(x)

23

In [422]:
np.min(x)

-24

In [423]:
np.median(x)

5.0

In [457]:
#사분위수
#데이터를 4구간으로 나눠서 각각 1/4,2/4,3/4 위치에 있는 수
#1사분위수 - 하위 25% / 2사분위수 - 중앙값 / 3사분위수 - 하위 75%

In [466]:
np.percentile(x,25)  #1사분위 수
np.percentile(x,50)  #2사분위 수
np.percentile(x,75)  #3사분위 수

10.0

In [ ]:
np.percentile(x,50)

In [425]:
np.random.seed(0)

In [426]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [427]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [428]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [435]:
#데이터 순서 바꾸기
#shuffle()
#자체 변환 하마수로 한번 사용하면 변수의 값이 바뀌기 때문에 주의!

x = np.arange(10)
x
np.random.shuffle(x)
x

array([5, 2, 3, 4, 1, 0, 9, 8, 7, 6])

In [456]:
#데이터 샘플링
#모집단에서 표본을 무작위 선택 , 표본선택 혹은 샘플링
#numpy.random.choice(a, size=None, replace=True, p=None)
    # replace : True이면 복원추출
    # p : 배열. 각 데이터가 선택될 수 있는 확률.

np.random.choice(5,5,replace =False)  #shuffle의 명령 동일
np.random.choice(5,3,replace = False) #3개만 선택
np.random.choice(5,10)  #반복해서 10개 선택
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0]) #선택 확률 다르게 해서 10개 선택

array([3, 3, 3, 2, 2, 3, 3, 3, 3, 2])

In [438]:
#난수 생성
#Numpy의 random패키지
    #rand : 0부터 1사이의 균일분포
    #randn : 표준 정규 분포
    #randint : 균일 분포의 정수 난수

In [439]:
np.random.rand(10)

array([0.33739616, 0.64817187, 0.36824154, 0.95715516, 0.14035078,
       0.87008726, 0.47360805, 0.80091075, 0.52047748, 0.67887953])

In [441]:
np.random.rand(3,5)  #shape 3 X 5

array([[0.44994999, 0.61306346, 0.90234858, 0.09928035, 0.96980907],
       [0.65314004, 0.17090959, 0.35815217, 0.75068614, 0.60783067],
       [0.32504723, 0.03842543, 0.63427406, 0.95894927, 0.65279032]])

In [443]:
#randn()
#평균이 0이고 표준편차가 1인 표준 정규 분포를 따르는 난수

np.random.randn(3,4)

array([[ 0.02686925,  1.05583713, -0.07318342, -0.66572066],
       [-0.04411241, -0.36326702, -0.01234481,  0.04212149],
       [ 1.95929589, -0.1984257 ,  0.33053441, -1.43582841]])

In [451]:
#randint()
#numpy.random.randint(low, high=None, size=None)
    #high는 범위에 포함 X / 입력하지 않으면 0~low사이의 숫자 / 입력하면 low~high사이의 숫자
    #size는 난수의 개수
    
np.random.randint(10,20,size=(3,5))


array([[19, 14, 14, 16, 14],
       [14, 13, 14, 14, 18],
       [14, 13, 17, 15, 15]])

In [7]:
#연습문제

#동전을 100번 던진 결과를 난수 발생 , 앞면:1 , 뒷면:0
#이때 앞면이 나올 확률

np.random.seed(0)
r = np.random.randint(0,2,size=100)
sum(r)/len(r)

0.56

In [6]:
#주사위를 100번 던져서 나오는 숫자를 난수 생성
#그 숫자들의 평균

np.random.seed(0)
a = np.random.randint(1,7,100)
a.mean()

3.42

In [468]:
#정수 데이터 카운팅
#데이터에서 중복되지 않는 값의 리스트 출력

np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [475]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a,return_counts=True)
index

array(['a', 'b', 'c'], dtype='<U1')

In [476]:
count

array([2, 2, 1], dtype=int64)

In [18]:
np1 = np.array([[1,2,3],[4,5,6]])
np2 = np.array([[7,8,9],[10,11,12]])

np1+np2


array([[ 8, 10, 12],
       [14, 16, 18]])

In [12]:
#연습문제 - 
a  = np.arange(1,10)
a * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [45]:
#연습문제 
#5번째 숫자만 1

a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [44]:
#연습문제
#역순

b = np.arange(50)
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [46]:
#연습문제
#빈 문자열을 갖는 shape이 (3,3,3)이고 type이 U10인 배열 생성

a = np.zeros((3,3,3),dtype = '<U10')
a

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [51]:
#np.full
#하나의 특정 값으로 배열을 채울때

a = np.full((3,3,3),'playdata')
a

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [57]:
np.arange(2,41,2).reshape(2,2,5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [61]:
#단위 행렬 (=항등행렬)
#주대각선의 원소가 모두 1이고 나머지는 모두 0인 정사각행렬
#np.eye(n)

np.eye(4,dtype='i')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [81]:
#데이터 타입 변경
#astype(dtype='')  / dtype 필수

np.random.seed(0)
B = np.random.randint(0,2,9)
B.astype(dtype= 'bool').reshape(3,3)    #bool대신에 ? 사용가능


array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [88]:
np.random.seed(0)
f = np.random.rand(10) * 10 
f.astype('int')

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3])

In [99]:
f = np.ones((10,10))
f[1:-1,1:-1] = 0
f

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [121]:
f = np.ones((10,10))
f[:,[0,-1]]=0
f[[0,-1],:]=0
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [144]:
#

z=np.ones((8,8))
z[1::2,::2] =0 
z[::2,1::2]=0
z

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [150]:
np.tile(np.eye(2),(4,4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [169]:
#boolean indexing
#같은 shape과 len의 boolean type의 값을 갖는 ndarray로 인덱싱

v = np.arange(0,11)
neg = np.array([True if i>3 and i<7 else False for i in range(0,11)])
v[neg] = v[neg] * -1
v

#강사님
a = np.arange(11)
a[(3<a) & (7>a)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [172]:
#1부터 100까지의 3의 배수를 갖는 1차원 배열 생성 후 전체의 합

a = np.arange(3,101,3)
a.sum()

1683

In [180]:
np.linspace(0.1,0.9,9)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [3]:
import numpy as np
#로또 번호 생성기
#자연수 이외의 값을 입력하면 다시 입력대기
#로또 번호는 1차원의 ndarray의 형태로 오름차순 정렬

while True :
    try: 
        count = int(input('로또 몇개 드릴까요?'))
        if count <= 0:
            raise Error
        numbers = np.arange(1,46)
        lottos = [np.sort(np.random.choice(numbers,6,replace=False)) for _ in range(count)]
        display(lottos)
        break
    except:
        print('자연수만 입력해주세요.')

로또 몇개 드릴까요? 2


[array([ 8, 16, 23, 27, 36, 38]), array([10, 18, 19, 30, 37, 41])]

In [34]:
#서버의 응답시간 데이터
#200ms를 넘기는 값의 개수 

resp_time = np. array([158,  85, 205,  24,  42, 175, 188, 149, 153, 171, 137,  55, 108,
                       199, 177, 209, 218,  76, 103, 189, 110, 192, 136, 119,   4, 102,
                       177, 212, 110,  37, 163,  32,  77,  22, 125, 184,  46, 139,  72,
                       168, 133, 209, 148,  47, 102,  65, 160,  56,  11,  96, 169, 118,
                        55, 135, 217,  49, 100,  85, 179,  15, 139, 199, 124, 142,  15,
                        49, 168, 171, 168, 177, 147,  23, 199,  26,  51,  42,  90, 128,
                       186, 169, 129,  70, 198, 111,  81, 150,  17, 177, 201,  10,  75,
                       199,  55, 151, 183, 152, 119, 193, 110, 204])


len(resp_time[resp_time > 200])

#강사님
(resp_time > 200).sum()

8

In [36]:
#사분위수 구하기

print(np.percentile(resp_time,25))
print(np.percentile(resp_time,50))
print(np.percentile(resp_time,75))

#강사님
for i,v in enumerate(range(25,76,25)):
    print(f'{i+1}분위({v}%) 값 : {np.percentile(resp_time,v)}ms')

71.5
131.0
175.5
1분위(25%) 값 : 71.5ms
2분위(50%) 값 : 131.0ms
3분위(75%) 값 : 175.5ms


In [32]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])

count = np.bincount(result,minlength=3)
winner_index =count.argmax()
print(f'{p[winner_index]}가 {count[winner_index]}표로 반장으로 선출되었습니다.')

뽀로로가 81표로 반장으로 선출되었습니다.
