<a href="https://colab.research.google.com/github/yulmu99/Playdata/blob/main/Deep_learning/1_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.Initializing a Tensor


In [ ]:
import numpy as np
import torch

## Directly form data

In [ ]:
data = [
    [1, 2], [3, 4], [5, 6]
]
data   #python list

[[1, 2], [3, 4], [5, 6]]

In [ ]:
data_tensor = torch.tensor(data)  #list -> tensor
data_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## From a Numpy array

In [ ]:
arr = np.array(data)    #array
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr = np.array(data)    
arr_tensor = torch.tensor(arr)   #array -> tensor

print(f'Numpy arr value: \n {arr} \n')
print(f'Tensor arr_tensor value: \n {arr_tensor} \n')

Numpy arr value: 
 [[1 2]
 [3 4]
 [5 6]] 

Tensor arr_tensor value: 
 tensor([[1, 2],
        [3, 4],
        [5, 6]]) 



In [ ]:
np.multiply(arr,2,out=arr)

print(f'Numpy arr after * 2 operation : \n {arr} \n')
print(f'Tensor arr_tensor value after modifying numpy array: \n {arr} \n') 

Numpy arr after * 2 operation : 
 [[ 2  4]
 [ 6  8]
 [10 12]] 

Tensor arr_tensor value after modifying numpy array: 
 [[ 2  4]
 [ 6  8]
 [10 12]] 



torch.from_numpy() -> 얕은 복사

## From another tensor

In [ ]:
x_ones = torch.ones_like(data_tensor)   #shape은 그대로 유지하고 값만 1로 
x_ones 


tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [ ]:
x_rand = torch.rand_like(data_tensor, dtype = torch.float)  #shape은 그대로 유지하고 값만 랜덤으로
x_rand

tensor([[0.4126, 0.6691],
        [0.6921, 0.8144],
        [0.8315, 0.1422]])

## With random or constant values

In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6891, 0.8338, 0.6761],
        [0.7562, 0.7624, 0.6289]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 2.Attributes of a Tensor

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 3.Operations on Tensor

In [ ]:
from torch.cuda import is_available

# We move our tensor to the GPU if available

if torch.cuda.is_available():
  tensor = tensor.to('cuda')

tensor.device

device(type='cuda', index=0)

## Indexing and Slicing

In [ ]:
data = [
    [1, 2, 3], [4, 5, 6], [7, 8, 9]
]
tensor = torch.tensor(data, dtype=torch.float)

print(tensor)
print('-'*50)

print('First row: ',tensor[0])
print('Last row: ',tensor[-1])
print('First column: ', tensor[:,0])
print('Last column1:', tensor[:,-1])
print('Last column2:', tensor[...,-1])

print('-'*50)
tensor[:,1] = 0
tensor[1] = 0
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
--------------------------------------------------
First row:  tensor([1., 2., 3.])
Last row:  tensor([7., 8., 9.])
First column:  tensor([1., 4., 7.])
Last column1: tensor([3., 6., 9.])
Last column2: tensor([3., 6., 9.])
--------------------------------------------------
tensor([[1., 0., 3.],
        [0., 0., 0.],
        [7., 0., 9.]])


## Joining tensors

In [ ]:
t0 = torch.cat([tensor, tensor], dim=0) # 행 방향으로 합치기
t0

tensor([[1., 0., 3.],
        [0., 0., 0.],
        [7., 0., 9.],
        [1., 0., 3.],
        [0., 0., 0.],
        [7., 0., 9.]])

In [ ]:
t1 = torch.cat([tensor, tensor], dim=1) # 열 방향으로 합치기
t1

tensor([[1., 0., 3., 1., 0., 3.],
        [0., 0., 0., 0., 0., 0.],
        [7., 0., 9., 7., 0., 9.]])

## Arithmethic Operations

### torch.mm

performs a matrix multiplication `without broadcasting`





In [ ]:
mat1 = torch.randn(2,3)
mat2 = torch.randn(3,3)

In [ ]:
mat1

tensor([[ 1.5987,  0.0734, -0.1398],
        [-0.6811,  0.6174, -0.2750]])

In [ ]:
mat2

tensor([[ 0.0791,  2.0352,  0.9989],
        [-0.8680, -1.1792, -1.3488],
        [ 0.3222,  0.6106, -0.5415]])

In [ ]:
torch.mm(mat1,mat2)

tensor([[ 0.0177,  3.0816,  1.5735],
        [-0.6784, -2.2821, -1.3642]])

In [ ]:
torch.mm(mat2,mat1)  #broadcasting이 적용되지 않아서 오류 발생

### torch.mul
performs a elementwise multiplication `with broadcasting` (Tensor) by (Tensor or Number)

In [ ]:
a = torch.randn(3)  # vector
a

tensor([-0.8767,  0.5854,  0.0723])

In [ ]:
torch.mul(a,100)

tensor([-87.6718,  58.5388,   7.2347])

In [ ]:
b = torch.randn(1,4)
b

tensor([[ 0.3322, -0.2339,  1.8751,  0.2751]])

In [ ]:
c = torch.randn(1,4)
c

tensor([[ 1.4303, -0.4398,  0.4229, -0.0160]])

In [ ]:
torch.mul(b,c)

tensor([[ 0.4752,  0.1029,  0.7929, -0.0044]])

In [ ]:
torch.mm(b,c)

mm와 mul의 차이는 broadcasting이 되는가? 안되는가?

###torch.matmul
matrix product `with broadcasting`
- 내적계산 


In [ ]:
# vector * vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
torch.matmul(tensor1, tensor2)  #벡터끼리 곱은 스칼라로 

tensor(-1.1684)

In [ ]:
torch.matmul(tensor1, tensor2).size()

torch.Size([])

In [ ]:
torch.mul(tensor1, tensor2)    

tensor([ 0.1283, -0.4288, -0.8678])

In [ ]:
# matrix x vector
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2)

tensor([ 0.4110, -0.2937,  3.6377])

In [ ]:
tensor1 ,tensor2

(tensor([[ 1.4614,  0.0480,  0.7553, -0.8300],
         [-0.6709,  0.1465, -0.3391, -0.1227],
         [ 1.1211, -1.5678, -0.9218, -0.3840]]),
 tensor([ 0.7832, -1.0789, -1.0883, -0.1689]))

In [ ]:
torch.matmul(tensor1, tensor2)

tensor([ 0.4110, -0.2937,  3.6377])

In [ ]:
torch.mul(tensor1, tensor2)

tensor([[ 1.1446, -0.0518, -0.8220,  0.1402],
        [-0.5255, -0.1581,  0.3691,  0.0207],
        [ 0.8780,  1.6916,  1.0032,  0.0648]])

In [ ]:
# batched matrix x broadcasted vector
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)

In [ ]:
tensor1 ,tensor2

(tensor([[[ 0.6905,  0.5284, -0.3423,  0.2416],
          [ 0.0177, -0.1010, -1.6637,  0.5731],
          [-0.1772,  0.0628, -1.2163, -0.7322]],
 
         [[ 1.6029, -1.0740,  0.2423, -0.0173],
          [ 0.2033,  0.4923, -0.0596,  1.0159],
          [ 0.9193, -0.6344, -0.1071,  0.4892]],
 
         [[ 1.9694,  0.5597,  1.4487,  0.1174],
          [ 0.5137, -1.5213,  0.2253,  0.0829],
          [-0.9639,  0.2176,  1.1066, -0.6055]],
 
         [[ 0.3732,  0.2728, -1.2808, -0.0677],
          [-0.2020,  0.0798,  0.4788, -0.9744],
          [ 0.3092, -1.1207,  0.7007, -0.0395]],
 
         [[-1.7374,  1.0679, -0.0049,  0.0244],
          [ 1.4768,  2.8780,  1.0624, -1.0649],
          [-0.1902, -0.6958,  1.7166, -0.4176]],
 
         [[-1.0236,  0.6371,  0.6961,  0.5503],
          [ 0.1041,  0.1366,  0.8120, -1.4820],
          [-0.4327,  0.0989,  1.0478, -1.8587]],
 
         [[-1.2478, -0.1068, -0.9871, -1.3013],
          [ 0.8194, -0.1905,  0.4581,  0.7736],
          [-2.3437,  1

In [ ]:
torch.matmul(tensor1, tensor2).shape 

torch.Size([10, 3])

In [ ]:
torch.mul(tensor1, tensor2).shape

torch.Size([10, 3, 4])

In [ ]:
# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

In [ ]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.mul(tensor1, tensor2).size()

RuntimeError: ignored

In [ ]:
# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

In [ ]:
torch.mul(tensor1, tensor2).size()

RuntimeError: ignored

### Single-element tensors 

In [ ]:
tensor2

tensor([[-0.4147, -1.5279,  0.6322,  0.4738, -0.5325],
        [ 0.7008,  0.8237,  0.5067,  1.3550,  0.8410],
        [-1.6480, -2.6051,  1.6421, -0.5680,  0.3758],
        [-0.0322, -1.2382, -0.7474, -0.3684,  0.7995]])

In [ ]:
agg = tensor2.sum()
agg 

tensor(-1.5321)

In [ ]:
agg_item = agg.item()   #python 연산을 하기 위해서 .item()
print(agg_item, type(agg_item))

-1.5321239233016968 <class 'float'>


### In-place operations

In [ ]:
print(tensor2, "\n")
print(f"{tensor2.add(5)}\n")
print('-'*50)
print(tensor2, "\n")
tensor2.add_(5) # inplace
print(tensor2)

tensor([[-0.4147, -1.5279,  0.6322,  0.4738, -0.5325],
        [ 0.7008,  0.8237,  0.5067,  1.3550,  0.8410],
        [-1.6480, -2.6051,  1.6421, -0.5680,  0.3758],
        [-0.0322, -1.2382, -0.7474, -0.3684,  0.7995]]) 

tensor([[4.5853, 3.4721, 5.6322, 5.4738, 4.4675],
        [5.7008, 5.8237, 5.5067, 6.3550, 5.8410],
        [3.3520, 2.3949, 6.6421, 4.4320, 5.3758],
        [4.9678, 3.7618, 4.2526, 4.6316, 5.7995]])

--------------------------------------------------
tensor([[-0.4147, -1.5279,  0.6322,  0.4738, -0.5325],
        [ 0.7008,  0.8237,  0.5067,  1.3550,  0.8410],
        [-1.6480, -2.6051,  1.6421, -0.5680,  0.3758],
        [-0.0322, -1.2382, -0.7474, -0.3684,  0.7995]]) 

tensor([[4.5853, 3.4721, 5.6322, 5.4738, 4.4675],
        [5.7008, 5.8237, 5.5067, 6.3550, 5.8410],
        [3.3520, 2.3949, 6.6421, 4.4320, 5.3758],
        [4.9678, 3.7618, 4.2526, 4.6316, 5.7995]])


# 4.Bridge with Numpy

## Tensor to Numpy array

In [ ]:
t = torch.ones(5)
print(f't:{t}')

n = t.numpy()   #tensor -> numpy
print(f'n:{n}')

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")  #.numpy()는 얕은 복사

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


## Numpy array to Tensor

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)
n,t

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


# 5. Dimension change

##reshape()
- reshape할 때는 데이터의 값은 변하지 않고 shape만 변경
- reshape은 데이터의 총 count가 일치해야 한다!

In [ ]:
x = torch.rand(2,3,4)
x.shape   #x의 총 count = 2*3*4 = 24

torch.Size([2, 3, 4])

In [ ]:
x.reshape(2, -1).shape  #(2,12)

torch.Size([2, 12])

In [ ]:
x.reshape(-1, 4).shape  #(6,4)

torch.Size([6, 4])

## permute()
- 인덱스를 기준으로 위치만 변경

In [ ]:
x = torch.rand(16, 32, 3)
x.shape

torch.Size([16, 32, 3])

In [ ]:
x.permute(2,1,0).shape

torch.Size([3, 32, 16])

## squeeze()
- 차원이 1인 차원을 제거해준다. 따로 차원을 설정하지 않으면 1인 차원을 모두 제거한다.

In [ ]:
x = torch.rand(1, 3, 1, 20, 1)
x.shape

torch.Size([1, 3, 1, 20, 1])

In [ ]:
x.squeeze().shape

torch.Size([3, 20])

In [ ]:
x.squeeze(dim=0).shape   #dim : 차원의 index값

torch.Size([3, 1, 20, 1])

In [ ]:
x.squeeze(dim=1).shape    #지정한 차원의 값이 1이 아닌 경우에는 변화X

torch.Size([1, 3, 1, 20, 1])

## unsqueeze()
- squeeze()의 반대로 1인 차원을 생성하는 함수이다. <br>그래서 어느 차원에 1인 차원을 생성할지 꼭 지정해주어야 한다.



In [ ]:
x = torch.rand(3, 20, 128)
x.shape

torch.Size([3, 20, 128])

In [ ]:
x.unsqueeze(dim=1).shape

torch.Size([3, 1, 20, 128])